/** Villes proposées dans les champs avec autocomplétion (liste indicative, non exhaustive). */
export const CITIES = [
  "Ouagadougou",
  "Bobo-Dioulasso",
  "Koudougou",
  "Banfora",
  "Ouahigouya",
  "Kaya",
  "Tenkodogo",
  "Dédougou",
  "Fada N'Gourma",
  "Abidjan",
  "Bamako",
  "Dakar",
  "Lomé",
  "Cotonou",
  "Niamey",
  "Paris",
  "Lyon",
  "Marseille",
  "Toulouse",
  "Nice",
  "Nantes",
  "Strasbourg",
  "Bordeaux",
  "Lille",
  "Rennes",
  "Montpellier",
];
