/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as ShellAdminRouteImport } from './routes/_shell.admin'
import { Route as ShellCoursesRouteImport } from './routes/_shell.courses'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellDocumentsRouteImport } from './routes/_shell.documents'
import { Route as ShellDrivingRouteImport } from './routes/_shell.driving'
import { Route as ShellGroupsRouteImport } from './routes/_shell.groups'
import { Route as ShellInstructorsRouteImport } from './routes/_shell.instructors'
import { Route as ShellMessagesRouteImport } from './routes/_shell.messages'
import { Route as ShellMonEspaceRouteImport } from './routes/_shell.mon-espace'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as ShellPaymentsRouteImport } from './routes/_shell.payments'
import { Route as ShellPlanningRouteImport } from './routes/_shell.planning'
import { Route as ShellQuestionsRouteImport } from './routes/_shell.questions'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellVehiclesRouteImport } from './routes/_shell.vehicles'
import { Route as ShellAssignmentsIndexRouteImport } from './routes/_shell.assignments.index'
import { Route as ShellAssignmentsAssignmentIdRouteImport } from './routes/_shell.assignments.$assignmentId'
import { Route as ShellExamsIndexRouteImport } from './routes/_shell.exams.index'
import { Route as ShellExamsExamIdRouteImport } from './routes/_shell.exams.$examId'
import { Route as ShellStudentsIndexRouteImport } from './routes/_shell.students.index'
import { Route as ShellStudentsStudentIdRouteImport } from './routes/_shell.students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAdminRoute = ShellAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCoursesRoute = ShellCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocumentsRoute = ShellDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDrivingRoute = ShellDrivingRouteImport.update({
  id: '/driving',
  path: '/driving',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGroupsRoute = ShellGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInstructorsRoute = ShellInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMessagesRoute = ShellMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMonEspaceRoute = ShellMonEspaceRouteImport.update({
  id: '/mon-espace',
  path: '/mon-espace',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPaymentsRoute = ShellPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPlanningRoute = ShellPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => ShellRoute,
} as any)
const ShellQuestionsRoute = ShellQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVehiclesRoute = ShellVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAssignmentsIndexRoute = ShellAssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAssignmentsAssignmentIdRoute =
  ShellAssignmentsAssignmentIdRouteImport.update({
    id: '/assignments/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellExamsIndexRoute = ShellExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExamsExamIdRoute = ShellExamsExamIdRouteImport.update({
  id: '/exams/$examId',
  path: '/exams/$examId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStudentsIndexRoute = ShellStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStudentsStudentIdRoute = ShellStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/admin': typeof ShellAdminRoute
  '/courses': typeof ShellCoursesRoute
  '/dashboard': typeof ShellDashboardRoute
  '/documents': typeof ShellDocumentsRoute
  '/driving': typeof ShellDrivingRoute
  '/groups': typeof ShellGroupsRoute
  '/instructors': typeof ShellInstructorsRoute
  '/messages': typeof ShellMessagesRoute
  '/mon-espace': typeof ShellMonEspaceRoute
  '/notifications': typeof ShellNotificationsRoute
  '/payments': typeof ShellPaymentsRoute
  '/planning': typeof ShellPlanningRoute
  '/questions': typeof ShellQuestionsRoute
  '/settings': typeof ShellSettingsRoute
  '/vehicles': typeof ShellVehiclesRoute
  '/assignments/$assignmentId': typeof ShellAssignmentsAssignmentIdRoute
  '/exams/$examId': typeof ShellExamsExamIdRoute
  '/students/$studentId': typeof ShellStudentsStudentIdRoute
  '/assignments/': typeof ShellAssignmentsIndexRoute
  '/exams/': typeof ShellExamsIndexRoute
  '/students/': typeof ShellStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/admin': typeof ShellAdminRoute
  '/courses': typeof ShellCoursesRoute
  '/dashboard': typeof ShellDashboardRoute
  '/documents': typeof ShellDocumentsRoute
  '/driving': typeof ShellDrivingRoute
  '/groups': typeof ShellGroupsRoute
  '/instructors': typeof ShellInstructorsRoute
  '/messages': typeof ShellMessagesRoute
  '/mon-espace': typeof ShellMonEspaceRoute
  '/notifications': typeof ShellNotificationsRoute
  '/payments': typeof ShellPaymentsRoute
  '/planning': typeof ShellPlanningRoute
  '/questions': typeof ShellQuestionsRoute
  '/settings': typeof ShellSettingsRoute
  '/vehicles': typeof ShellVehiclesRoute
  '/assignments/$assignmentId': typeof ShellAssignmentsAssignmentIdRoute
  '/exams/$examId': typeof ShellExamsExamIdRoute
  '/students/$studentId': typeof ShellStudentsStudentIdRoute
  '/assignments': typeof ShellAssignmentsIndexRoute
  '/exams': typeof ShellExamsIndexRoute
  '/students': typeof ShellStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/_shell/admin': typeof ShellAdminRoute
  '/_shell/courses': typeof ShellCoursesRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/documents': typeof ShellDocumentsRoute
  '/_shell/driving': typeof ShellDrivingRoute
  '/_shell/groups': typeof ShellGroupsRoute
  '/_shell/instructors': typeof ShellInstructorsRoute
  '/_shell/messages': typeof ShellMessagesRoute
  '/_shell/mon-espace': typeof ShellMonEspaceRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/payments': typeof ShellPaymentsRoute
  '/_shell/planning': typeof ShellPlanningRoute
  '/_shell/questions': typeof ShellQuestionsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/vehicles': typeof ShellVehiclesRoute
  '/_shell/assignments/$assignmentId': typeof ShellAssignmentsAssignmentIdRoute
  '/_shell/exams/$examId': typeof ShellExamsExamIdRoute
  '/_shell/students/$studentId': typeof ShellStudentsStudentIdRoute
  '/_shell/assignments/': typeof ShellAssignmentsIndexRoute
  '/_shell/exams/': typeof ShellExamsIndexRoute
  '/_shell/students/': typeof ShellStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/inscription'
    | '/admin'
    | '/courses'
    | '/dashboard'
    | '/documents'
    | '/driving'
    | '/groups'
    | '/instructors'
    | '/messages'
    | '/mon-espace'
    | '/notifications'
    | '/payments'
    | '/planning'
    | '/questions'
    | '/settings'
    | '/vehicles'
    | '/assignments/$assignmentId'
    | '/exams/$examId'
    | '/students/$studentId'
    | '/assignments/'
    | '/exams/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/inscription'
    | '/admin'
    | '/courses'
    | '/dashboard'
    | '/documents'
    | '/driving'
    | '/groups'
    | '/instructors'
    | '/messages'
    | '/mon-espace'
    | '/notifications'
    | '/payments'
    | '/planning'
    | '/questions'
    | '/settings'
    | '/vehicles'
    | '/assignments/$assignmentId'
    | '/exams/$examId'
    | '/students/$studentId'
    | '/assignments'
    | '/exams'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/connexion'
    | '/inscription'
    | '/_shell/admin'
    | '/_shell/courses'
    | '/_shell/dashboard'
    | '/_shell/documents'
    | '/_shell/driving'
    | '/_shell/groups'
    | '/_shell/instructors'
    | '/_shell/messages'
    | '/_shell/mon-espace'
    | '/_shell/notifications'
    | '/_shell/payments'
    | '/_shell/planning'
    | '/_shell/questions'
    | '/_shell/settings'
    | '/_shell/vehicles'
    | '/_shell/assignments/$assignmentId'
    | '/_shell/exams/$examId'
    | '/_shell/students/$studentId'
    | '/_shell/assignments/'
    | '/_shell/exams/'
    | '/_shell/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/admin': {
      id: '/_shell/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ShellAdminRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/courses': {
      id: '/_shell/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof ShellCoursesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/documents': {
      id: '/_shell/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof ShellDocumentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/driving': {
      id: '/_shell/driving'
      path: '/driving'
      fullPath: '/driving'
      preLoaderRoute: typeof ShellDrivingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/groups': {
      id: '/_shell/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof ShellGroupsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/instructors': {
      id: '/_shell/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof ShellInstructorsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/messages': {
      id: '/_shell/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof ShellMessagesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/mon-espace': {
      id: '/_shell/mon-espace'
      path: '/mon-espace'
      fullPath: '/mon-espace'
      preLoaderRoute: typeof ShellMonEspaceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/payments': {
      id: '/_shell/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof ShellPaymentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/planning': {
      id: '/_shell/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof ShellPlanningRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/questions': {
      id: '/_shell/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof ShellQuestionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/vehicles': {
      id: '/_shell/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof ShellVehiclesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/assignments/': {
      id: '/_shell/assignments/'
      path: '/assignments'
      fullPath: '/assignments/'
      preLoaderRoute: typeof ShellAssignmentsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/assignments/$assignmentId': {
      id: '/_shell/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof ShellAssignmentsAssignmentIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/exams/': {
      id: '/_shell/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof ShellExamsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/exams/$examId': {
      id: '/_shell/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof ShellExamsExamIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/students/': {
      id: '/_shell/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof ShellStudentsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/students/$studentId': {
      id: '/_shell/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof ShellStudentsStudentIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAdminRoute: typeof ShellAdminRoute
  ShellCoursesRoute: typeof ShellCoursesRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDocumentsRoute: typeof ShellDocumentsRoute
  ShellDrivingRoute: typeof ShellDrivingRoute
  ShellGroupsRoute: typeof ShellGroupsRoute
  ShellInstructorsRoute: typeof ShellInstructorsRoute
  ShellMessagesRoute: typeof ShellMessagesRoute
  ShellMonEspaceRoute: typeof ShellMonEspaceRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellPaymentsRoute: typeof ShellPaymentsRoute
  ShellPlanningRoute: typeof ShellPlanningRoute
  ShellQuestionsRoute: typeof ShellQuestionsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellVehiclesRoute: typeof ShellVehiclesRoute
  ShellAssignmentsAssignmentIdRoute: typeof ShellAssignmentsAssignmentIdRoute
  ShellExamsExamIdRoute: typeof ShellExamsExamIdRoute
  ShellStudentsStudentIdRoute: typeof ShellStudentsStudentIdRoute
  ShellAssignmentsIndexRoute: typeof ShellAssignmentsIndexRoute
  ShellExamsIndexRoute: typeof ShellExamsIndexRoute
  ShellStudentsIndexRoute: typeof ShellStudentsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAdminRoute: ShellAdminRoute,
  ShellCoursesRoute: ShellCoursesRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDocumentsRoute: ShellDocumentsRoute,
  ShellDrivingRoute: ShellDrivingRoute,
  ShellGroupsRoute: ShellGroupsRoute,
  ShellInstructorsRoute: ShellInstructorsRoute,
  ShellMessagesRoute: ShellMessagesRoute,
  ShellMonEspaceRoute: ShellMonEspaceRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellPaymentsRoute: ShellPaymentsRoute,
  ShellPlanningRoute: ShellPlanningRoute,
  ShellQuestionsRoute: ShellQuestionsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellVehiclesRoute: ShellVehiclesRoute,
  ShellAssignmentsAssignmentIdRoute: ShellAssignmentsAssignmentIdRoute,
  ShellExamsExamIdRoute: ShellExamsExamIdRoute,
  ShellStudentsStudentIdRoute: ShellStudentsStudentIdRoute,
  ShellAssignmentsIndexRoute: ShellAssignmentsIndexRoute,
  ShellExamsIndexRoute: ShellExamsIndexRoute,
  ShellStudentsIndexRoute: ShellStudentsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
